seed: 42
n_actions: 50
nrows: 2000000
embedding_dim: 16
hidden_sizes: [512, 256]
batch_size: 1024
lr: 1e-3
entropy_coef: 0.001
clip_grad_norm: 5.0
epochs: 5
clip_weight: 50.0
device: cpu   # change to cuda if you have GPU